export const palabrasAPI = [
  { palabra: "me", esLenguajeProgramacion: false, maxPrints: null },
  { palabra: "JavaScript", esLenguajeProgramacion: true, maxPrints: null },
  { palabra: "el", esLenguajeProgramacion: false, maxPrints: null },
  { palabra: "la", esLenguajeProgramacion: false, maxPrints: null },
  { palabra: "gusta", esLenguajeProgramacion: false, maxPrints: null },
  { palabra: "odio", esLenguajeProgramacion: false, maxPrints: null },
  { palabra: "no", esLenguajeProgramacion: false, maxPrints: null },
  { palabra: "muy", esLenguajeProgramacion: false, maxPrints: null },
  { palabra: "y", esLenguajeProgramacion: false, maxPrints: null },
  { palabra: "Java", esLenguajeProgramacion: true, maxPrints: null },
  { palabra: "mucho", esLenguajeProgramacion: false, maxPrints: null },
  { palabra: "poco", esLenguajeProgramacion: false, maxPrints: null },
  { palabra: "programador", esLenguajeProgramacion: false, maxPrints: null },
  { palabra: "amigo", esLenguajeProgramacion: false, maxPrints: null },
  { palabra: "programadora", esLenguajeProgramacion: false, maxPrints: null },
  { palabra: "amiga", esLenguajeProgramacion: false, maxPrints: null },
  { palabra: "soy", esLenguajeProgramacion: false, maxPrints: null },
  { palabra: "también", esLenguajeProgramacion: false, maxPrints: null },
  { palabra: "pero", esLenguajeProgramacion: false, maxPrints: null },
  { palabra: "gustan", esLenguajeProgramacion: false, maxPrints: null },
  { palabra: "gatos", esLenguajeProgramacion: false, maxPrints: null },
  { palabra: "los", esLenguajeProgramacion: false, maxPrints: null },
  { palabra: "perros", esLenguajeProgramacion: false, maxPrints: null },
];
